const topicInput=document.getElementById("topic");
const categoryInput=document.getElementById("category");
const difficultyInput=document.getElementById("difficulty");
const questionCountInput=document.getElementById("questionCount");
const generateAIButton=document.getElementById("generateAI");

function getQuizPrompt({topic,category,difficulty,count,sourceText}){

    const sourceInstruction=sourceText
        ? `Create the quiz only from this study material:\n\n${sourceText}`
        : `Create the quiz about this topic: ${topic}\nCategory: ${category}`;

    return `
You are SmartQuiz AI, a quiz generator for school students.

${sourceInstruction}

Difficulty: ${difficulty}
Number of questions: ${count}

Return ONLY valid JSON. Do not include markdown, headings, notes, or code fences.

JSON format:
[
  {
    "question": "Question text",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "answer": "One exact option from options",
    "explanation": "Short explanation"
  }
]

Rules:
- Generate exactly ${count} questions.
- Each question must have exactly 4 options.
- The answer must exactly match one option.
- Keep questions clear for high school students.
`;

}

function extractJsonArray(text){

    const cleaned=text
        .replace(/```json/gi,"")
        .replace(/```/g,"")
        .trim();

    const start=cleaned.indexOf("[");
    const end=cleaned.lastIndexOf("]");

    if(start===-1 || end===-1 || end<=start){
        throw new Error("AI did not return a JSON array.");
    }

    return cleaned.slice(start,end+1);

}

function validateQuestions(questions,count){

    if(!Array.isArray(questions)){
        throw new Error("AI response is not a question list.");
    }

    if(questions.length!==count){
        throw new Error(`AI returned ${questions.length} questions instead of ${count}. Please try again.`);
    }

    questions.forEach((item,index)=>{

        if(!item.question || !Array.isArray(item.options) || item.options.length!==4 || !item.answer){
            throw new Error(`Question ${index+1} is not in the correct format.`);
        }

        if(!item.options.includes(item.answer)){
            throw new Error(`Question ${index+1} answer does not match its options.`);
        }

        if(!item.explanation){
            item.explanation="Generated by AI.";
        }

    });

    return questions;

}

async function generateQuestionsWithAI(settings){

    if(!GROQ_API_KEY || GROQ_API_KEY==="PASTE_YOUR_GROQ_API_KEY_HERE"){
        throw new Error("Please paste your Groq API key in config.js first.");
    }

    const response=await fetch("https://api.groq.com/openai/v1/chat/completions",{
        method:"POST",
        headers:{
            "Content-Type":"application/json",
            "Authorization":`Bearer ${GROQ_API_KEY}`
        },
        body:JSON.stringify({
            model:GROQ_MODEL,
            temperature:.7,
            messages:[
                {
                    role:"user",
                    content:getQuizPrompt(settings)
                }
            ]
        })
    });

    const data=await response.json();

    if(!response.ok){
        throw new Error(data.error?.message || "Groq API request failed.");
    }

    const content=data.choices?.[0]?.message?.content;

    if(!content){
        throw new Error("AI did not return quiz content.");
    }

    const questions=JSON.parse(extractJsonArray(content));

    return validateQuestions(questions,settings.count);

}

async function generateAIQuiz(){

    const topic=topicInput.value.trim();
    const category=categoryInput.value;
    const difficulty=difficultyInput.value;
    const count=Number(questionCountInput.value);

    if(!topic){
        topicInput.focus();
        alert("Please enter a topic for the quiz.");
        return;
    }

    showLoading("Connecting to AI and generating your quiz.");

    try{

        const questions=await generateQuestionsWithAI({
            topic,
            category,
            difficulty,
            count
        });

        startQuiz({
            title:`${topic} Quiz`,
            source:"AI",
            questions
        });

    }catch(error){

        alert(error.message);
        showHome();

    }

}

generateAIButton.addEventListener("click",generateAIQuiz);
